[build]
  publish = "."

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/booking"
  to = "/booking.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/"
  status = 200
